// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmHH9i_xZWgtVDH4sfVbhZE8ClDZds_0',
    appId: '1:909680833578:web:ceaf8285b4f6d6427d7f53',
    messagingSenderId: '909680833578',
    projectId: 'missao-app-192b0',
    authDomain: 'missao-app-192b0.firebaseapp.com',
    storageBucket: 'missao-app-192b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98K_3Yc1ByrDfMHkrBc9b5m8HZ95zzaY',
    appId: '1:909680833578:android:3369450fede9e58b7d7f53',
    messagingSenderId: '909680833578',
    projectId: 'missao-app-192b0',
    storageBucket: 'missao-app-192b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNyWbvwXPqxyUuQU4158e2D01A9_634U',
    appId: '1:909680833578:ios:92995b53fb77220a7d7f53',
    messagingSenderId: '909680833578',
    projectId: 'missao-app-192b0',
    storageBucket: 'missao-app-192b0.firebasestorage.app',
    iosBundleId: 'com.example.missaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNyWbvwXPqxyUuQU4158e2D01A9_634U',
    appId: '1:909680833578:ios:92995b53fb77220a7d7f53',
    messagingSenderId: '909680833578',
    projectId: 'missao-app-192b0',
    storageBucket: 'missao-app-192b0.firebasestorage.app',
    iosBundleId: 'com.example.missaoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChmHH9i_xZWgtVDH4sfVbhZE8ClDZds_0',
    appId: '1:909680833578:web:536057fecab0a8e17d7f53',
    messagingSenderId: '909680833578',
    projectId: 'missao-app-192b0',
    authDomain: 'missao-app-192b0.firebaseapp.com',
    storageBucket: 'missao-app-192b0.firebasestorage.app',
  );
}
